### ISSUE TITLE
Algoritmo que encontre um caminho

### ISSUE THREAD

**Issue by BlueDi** [killghost15/IART#10]
É preciso um algoritmo que encontre o caminho pelas peças para ver se consegue chegar ao outro lado.
Se conseguir há um vencedor.

**Comment by killghost15** [comment]
falta a opção de ligar por diagonal no backtracking é uma opção não ter mas o jogo dá essa instrução de  se poder portanto pode ter essa opção

**Comment by killghost15** [comment]
já funciona falta a nova issue
